// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA97KEIR_qlqiNnEd5eC6F0Yh75VgG1lMY',
    appId: '1:553874508442:web:28f0dc1a3fa350f7f7ad23',
    messagingSenderId: '553874508442',
    projectId: 'photo-ai-app-51f68',
    authDomain: 'photo-ai-app-51f68.firebaseapp.com',
    storageBucket: 'photo-ai-app-51f68.firebasestorage.app',
    measurementId: 'G-Q0LEF9J5VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf4Q9iLt4MY22VLGDrWaZGcBi-IcVR5BM',
    appId: '1:553874508442:android:7f3ec382d00cbb56f7ad23',
    messagingSenderId: '553874508442',
    projectId: 'photo-ai-app-51f68',
    storageBucket: 'photo-ai-app-51f68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY_fBDdX5msmR5wxS55zEgYnGQm5MgwM0',
    appId: '1:553874508442:ios:7c2ba51c2875b5b3f7ad23',
    messagingSenderId: '553874508442',
    projectId: 'photo-ai-app-51f68',
    storageBucket: 'photo-ai-app-51f68.firebasestorage.app',
    iosClientId: '553874508442-7312ngn6ur3di75oeu8h8vtapjo10k2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY_fBDdX5msmR5wxS55zEgYnGQm5MgwM0',
    appId: '1:553874508442:ios:7c2ba51c2875b5b3f7ad23',
    messagingSenderId: '553874508442',
    projectId: 'photo-ai-app-51f68',
    storageBucket: 'photo-ai-app-51f68.firebasestorage.app',
    iosClientId: '553874508442-7312ngn6ur3di75oeu8h8vtapjo10k2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA97KEIR_qlqiNnEd5eC6F0Yh75VgG1lMY',
    appId: '1:553874508442:web:f2d0d1fa788bcab1f7ad23',
    messagingSenderId: '553874508442',
    projectId: 'photo-ai-app-51f68',
    authDomain: 'photo-ai-app-51f68.firebaseapp.com',
    storageBucket: 'photo-ai-app-51f68.firebasestorage.app',
    measurementId: 'G-Z0TV7X701F',
  );

}